services:
  trustnow-auth-db:
    container_name: trustnow-auth-db
    image: postgis/postgis:16-3.4
    environment:
      LANG: en_US.utf8
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "6464:${POSTGRES_PORT}"
    networks:
      - trustnow_auth_network
    restart: always
    volumes:
      - trustnow_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME}"]
      interval: 30s
      timeout: 10s
      retries: 5

  trustnow-auth-backend:
    container_name: trustnow-auth-backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "9080:${SERVER_PORT}"
    networks:
      - trustnow_auth_network
    restart: always
    depends_on:
      trustnow-auth-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://${HEALTHCHECK_HOST}:${HEALTHCHECK_PORT}/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  trustnow_auth_network:
    driver: bridge

volumes:
  trustnow_db_data:
    driver: local
